name: Build and Push Container

on:
  push:
    branches: [main]
    paths:
      - 'backpipe/**'           # ✅ Only trigger on backpipe changes
      - 'frontend/**'           # ✅ Only trigger on frontend changes
      - 'VetApi.UnitTests/**'   # ✅ Include unit test projects
      - 'VetApi.IntegrationTests/**' # ✅ Include integration test projects
      - 'VetApi.sln'            # ✅ Include root solution file
      - '.github/workflows/*.yml' # ✅ Include workflow file itself
      - 'VetApi.Deployment.sln'
      - 'Dockerfile'            # ✅ Include Dockerfile

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/amri0faz31/mythepipe/vetapp:latest
            ghcr.io/amri0faz31/mythepipe/vetapp:${{ github.sha }}