name: CI - Feature Branch Unit Tests

on:
  push:
    branches: ['feature/*']
    paths-ignore: ['*.md']

jobs:
  backend-unit-tests:
    runs-on: ubuntu-latest
    permissions: 
      checks: write    # <- ADD THIS LINE
      contents: read   # <- AND THIS ONE
    steps:  # <- REMOVED defaults.working-directory
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Run Unit Tests
        run: dotnet test VetApi.UnitTests/ --no-build --configuration Release --verbosity normal --logger trx --results-directory VetApi.UnitTests/TestResults

      - name: Publish Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: .NET Unit Tests
          path: VetApi.UnitTests/TestResults/*.trx  # <- SIMPLER PATH
          reporter: dotnet-trx