name: CI - Feature Branch Unit Tests

on:
  push:
    branches: ['feature/*']  # <- FIXED: Changed from 'feature/**' to 'feature/*'
    paths-ignore: ['*.md']   # Skip if only docs change

jobs:
  backend-unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backpipe/VetApi
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Run Unit Tests
        run: dotnet test ../../VetApi.UnitTests/ --no-build --configuration Release --verbosity normal

      # REMOVE these advanced steps for now to keep it simple
      # - name: Publish Test Results
      #   uses: dorny/test-reporter@v1
      #   if: always()
      #   with:
      #     name: .NET Unit Tests
      #     path: ../../VetApi.UnitTests/TestResults/*.trx
      #     reporter: dotnet-trx

      # - name: Publish Test Coverage
      #   uses: codecov/codecov-action@v4
      #   if: always()
      #   with:
      #     files: ../../VetApi.UnitTests/coverage/**/coverage.cobertura.xml
      #     token: ${{ secrets.CODECOV_TOKEN }}