name: Deploy from GHCR

on:
  workflow_run:
    workflows: ["Build and Push Container"]
    types: [completed]
    branches: [main]
    #hello
    #hello2

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Create Deployment Annotation
        run: |  
          echo "Deployed image: ghcr.io/amri0faz31/mythepipe/vetapp:latest"
          echo "Deployment time: $(date)"
          echo "Git commit: ${{ github.sha }}"

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          images: ghcr.io/amri0faz31/mythepipe/vetapp:latest
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
